name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [gcc, clang]
        cpp_std: [17]
        exclude:
          - os: windows-latest
            compiler: clang
          - os: macos-latest
            compiler: gcc

    steps:
    - uses: actions/checkout@v3

    - name: Set up C++ compiler (Ubuntu GCC)
      if: matrix.compiler == 'gcc' && matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake

    - name: Set up C++ compiler (Ubuntu Clang)
      if: matrix.compiler == 'clang' && matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y clang cmake

    - name: Set up C++ compiler (Windows)
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          mingw-w64-x86_64-toolchain
          cmake

    - name: Set up C++ compiler (macOS Clang)
      if: matrix.os == 'macos-latest'
      run: |
        brew install llvm cmake

    - name: Create build directory
      run: |
        mkdir -p build
        cd build

    - name: Configure CMake
      working-directory: ${{ github.workspace }}/build
      run: |
        cmake ${{ github.workspace }} \
          -DCMAKE_CXX_STANDARD=${{ matrix.cpp_std }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler == 'gcc' && 'g++' || 'clang++' }} \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_CXX_FLAGS="-O3"

    - name: Build
      working-directory: ${{ github.workspace }}/build
      run: cmake --build . --config Release --parallel

    - name: Run tests
      working-directory: ${{ github.workspace }}/build
      run: ctest --output-on-failure --parallel 