name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [gcc, clang]
        cpp_std: [17, 20]
        exclude:
          - os: windows-latest
            compiler: clang
          - os: macos-latest
            compiler: gcc

    steps:
    - uses: actions/checkout@v3

    - name: Set up CMake
      uses: actions/setup-cmake@v2

    - name: Set up C++ compiler
      if: matrix.compiler == 'gcc' && matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-${{ matrix.cpp_std }}

    - name: Set up C++ compiler
      if: matrix.compiler == 'gcc' && matrix.os == 'windows-latest'
      run: |
        choco install mingw -y
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Set up C++ compiler
      if: matrix.compiler == 'clang' && matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y clang

    - name: Set up C++ compiler
      if: matrix.compiler == 'clang' && matrix.os == 'macos-latest'
      run: |
        brew install llvm

    - name: Create build directory
      run: mkdir build && cd build

    - name: Configure CMake
      run: |
        cmake .. \
          -DCMAKE_CXX_STANDARD=${{ matrix.cpp_std }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler == 'gcc' && 'g++' || 'clang++' }} \
          -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build . --config Release

    - name: Run tests
      run: ctest --output-on-failure 