name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        cpp_std: [20]

    steps:
    - uses: actions/checkout@v3

    - name: Set up C++ compiler (GCC)
      if: matrix.compiler == 'gcc'
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake ninja-build
        echo "CC=gcc" >> $GITHUB_ENV
        echo "CXX=g++" >> $GITHUB_ENV

    - name: Set up C++ compiler (Clang)
      if: matrix.compiler == 'clang'
      run: |
        sudo apt-get update
        sudo apt-get install -y clang cmake ninja-build
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV

    - name: Create build directory
      run: mkdir -p build

    - name: Configure CMake
      working-directory: ${{ github.workspace }}/build
      run: |
        cmake .. \
          -G Ninja \
          -DCMAKE_CXX_STANDARD=${{ matrix.cpp_std }} \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_CXX_FLAGS="-Wall -Wextra -O3"

    - name: Build
      working-directory: ${{ github.workspace }}/build
      run: ninja

    - name: Run tests
      working-directory: ${{ github.workspace }}/build
      run: ctest --output-on-failure --parallel 